### ISSUE TITLE
Is anyone flashing this to their X6? 

### ISSUE THREAD

**Issue by yknip0** [julyworlds/openwrt-cudy-x6-firmware#1]
It appears this has not been updated since November 2021, except perhaps for overnight updates to open-wrt. Has anyone tried to use it on their X6? Discúlpame por inapropiado 'issue'

**Comment by VTEX999** [comment]
Yes actually!  It works well.

**Comment by VTEX999** [comment]
The only issue is there doesn't appear to be a recovery.bin anywhere public for the X6 (that I have found), so just beware that there may not be any going back.  If anyone does have a recovery.bin for the X6, please post a link!

**Comment by julyworlds** [comment]
Yes, I own a Cudy X6 and I am using it. Closing the issue :).

About the recovery.bin @VTEX999 , you can find the stock firmware in their website https://www.cudytech.com/x6_software_download

**Comment by yknip0** [comment]
> The only issue is there doesn't appear to be a recovery.bin anywhere public for the X6 (that I have found), so just beware that there may not be any going back. If anyone does have a recovery.bin for the X6, please post a link!

The tftp client on X6 looks for recovery.bin on the server. After you download as above, you must rename X6-R13-1.12.7-20220123-205651-flash.bin as recovery.bin...
