### ISSUE TITLE
no wireless in network

### ISSUE THREAD

**Issue by MrErr** [julyworlds/openwrt-cudy-x6-firmware#2]
I installed the latest snpashot [snapshot-2022.05.24-0557]. Under Network menu, there isn't a selection for wireless. In the menu status->overview, there isn't a section for wireless either. Is there something that needs to be done to able to see the wireless ports?

I also tried the previous snapshot and it has the same issue.

**Comment by julyworlds** [comment]
Oh I will check the configs, maybe I missed the wireless drivers last time I updated them. Thanks for letting me know.

**Comment by julyworlds** [comment]
I just checked and the snapshot version is missing the wireless, but stable should work fine.

In fact im using that right now and wireless works.

I will trigger the builds for the snapshot after the config is fixed. Closing the issue.
