### ISSUE TITLE
Package nano is not available

### ISSUE THREAD

**Issue by nospam2k** [julyworlds/openwrt-cudy-x6-firmware#3]
I'm not sure how this version of openwrt relates with opkg repositories, but nano isn't available. Is there an alternative solution to get nano onto cudy x6?

OpenWrt 21.02-SNAPSHOT r16649-a5924c51f1 / LuCI openwrt-21.02 branch git-22.184.38437-cbf33ce

**Comment by julyworlds** [comment]
Hello, the repository that is used is the snapshot repository from openwrt. Sometimes when they do updates it takes a while for all the packages to be available.

Also you can use the text editor `vi` it should be available by default.
