### ISSUE TITLE
ddns not able to work due to missing packages (curl, bind-host)

### ISSUE THREAD

**Issue by nospam2k** [julyworlds/openwrt-cudy-x6-firmware#4]
Similar problem of missing the packages from opkg
![Screen Shot 2022-07-18 at 2 26 49 PM](https://user-images.githubusercontent.com/1284287/179620352-0772e49d-2a5b-48e4-98ba-b217b3ce7e13.png)

**Comment by julyworlds** [comment]
Hello, same as the other issue, the repository that is used is the snapshot repository from openwrt. Sometimes when they do updates it takes a while for all the packages to be available.

Those packages are not necessary for ddns they are optional, that being said you should be able to install them using `opkg` when the repository gets updated.
