### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by rei-zero246** [julyworlds/openwrt-cudy-x6-firmware#5]
I am trying to install the newer OpenWrt firmware from the stock Cudy X6 firmware.

X6-R13-1.13.6-20220314-115945-flash.bin
X6-R13-1.12.7-20220123-205651-flash.bin

I have tried several versions from openwrt-22.03.0-rc4 to the latest snapshot (yours and OpenWrt).

I tried flashing from the restore option and the flashing option
![image](https://user-images.githubusercontent.com/66904012/227809766-7b3eaf5b-7173-433a-8a8d-f0a81cfbb68c.png)

Every one fails, from initramfs to sysupgrade and I have reset the device after each attempt.

Am I missing something?
![image](https://user-images.githubusercontent.com/66904012/227809824-a26dcb6d-21d8-44d0-86d0-b926961b0204.png)

**Comment by julyworlds** [comment]
Hi, not sure what is the status of the current stock firmware but to get access to the openwrt firmwares it used to be this way:
```
1    Download and flash the manufacturer's built OpenWRT image available at http://www.cudytech.com/openwrt_software_download (Need to install first due to signed firmware verification)

 2   Install any OpenWRT image via luci (System -> Backup/Flash firmware) Be sure to NOT keep settings. The force upgrade might need to be checked due to differences in router naming conventions.

```

**Comment by rei-zero246** [comment]
Yes, sorry, I decided to check what the zip actually contained as I thought it was just the current version that I already downloaded RE: stock firmware. I flashed the .bin in from the manufacturer's page and realized what it was. I just came back and saw your prompt response now on OpenWrt with your firmware; thank you.
